/* auto-generated, do not edit */

export const VERSION_NUMBER = 3044002;
export const OK = 0;
export const ERROR = 1;
export const INTERNAL = 2;
export const PERM = 3;
export const ABORT = 4;
export const BUSY = 5;
export const LOCKED = 6;
export const NOMEM = 7;
export const READONLY = 8;
export const INTERRUPT = 9;
export const IOERR = 10;
export const CORRUPT = 11;
export const NOTFOUND = 12;
export const FULL = 13;
export const CANTOPEN = 14;
export const PROTOCOL = 15;
export const EMPTY = 16;
export const SCHEMA = 17;
export const TOOBIG = 18;
export const CONSTRAINT = 19;
export const MISMATCH = 20;
export const MISUSE = 21;
export const NOLFS = 22;
export const AUTH = 23;
export const FORMAT = 24;
export const RANGE = 25;
export const NOTADB = 26;
export const NOTICE = 27;
export const WARNING = 28;
export const ROW = 100;
export const DONE = 101;
export const ERROR_MISSING_COLLSEQ = 257;
export const ERROR_RETRY = 513;
export const ERROR_SNAPSHOT = 769;
export const IOERR_READ = 266;
export const IOERR_SHORT_READ = 522;
export const IOERR_WRITE = 778;
export const IOERR_FSYNC = 1034;
export const IOERR_DIR_FSYNC = 1290;
export const IOERR_TRUNCATE = 1546;
export const IOERR_FSTAT = 1802;
export const IOERR_UNLOCK = 2058;
export const IOERR_RDLOCK = 2314;
export const IOERR_DELETE = 2570;
export const IOERR_BLOCKED = 2826;
export const IOERR_NOMEM = 3082;
export const IOERR_ACCESS = 3338;
export const IOERR_CHECKRESERVEDLOCK = 3594;
export const IOERR_LOCK = 3850;
export const IOERR_CLOSE = 4106;
export const IOERR_DIR_CLOSE = 4362;
export const IOERR_SHMOPEN = 4618;
export const IOERR_SHMSIZE = 4874;
export const IOERR_SHMLOCK = 5130;
export const IOERR_SHMMAP = 5386;
export const IOERR_SEEK = 5642;
export const IOERR_DELETE_NOENT = 5898;
export const IOERR_MMAP = 6154;
export const IOERR_GETTEMPPATH = 6410;
export const IOERR_CONVPATH = 6666;
export const IOERR_VNODE = 6922;
export const IOERR_AUTH = 7178;
export const IOERR_BEGIN_ATOMIC = 7434;
export const IOERR_COMMIT_ATOMIC = 7690;
export const IOERR_ROLLBACK_ATOMIC = 7946;
export const IOERR_DATA = 8202;
export const IOERR_CORRUPTFS = 8458;
export const IOERR_IN_PAGE = 8714;
export const CANTOPEN_NOTEMPDIR = 270;
export const CANTOPEN_ISDIR = 526;
export const CANTOPEN_FULLPATH = 782;
export const CANTOPEN_CONVPATH = 1038;
export const CANTOPEN_DIRTYWAL = 1294;
export const CANTOPEN_SYMLINK = 1550;
export const CORRUPT_VTAB = 267;
export const CORRUPT_SEQUENCE = 523;
export const CORRUPT_INDEX = 779;
export const READONLY_RECOVERY = 264;
export const READONLY_CANTLOCK = 520;
export const READONLY_ROLLBACK = 776;
export const READONLY_DBMOVED = 1032;
export const READONLY_CANTINIT = 1288;
export const READONLY_DIRECTORY = 1544;
export const ABORT_ROLLBACK = 516;
export const CONSTRAINT_CHECK = 275;
export const CONSTRAINT_COMMITHOOK = 531;
export const CONSTRAINT_FOREIGNKEY = 787;
export const CONSTRAINT_FUNCTION = 1043;
export const CONSTRAINT_NOTNULL = 1299;
export const CONSTRAINT_PRIMARYKEY = 1555;
export const CONSTRAINT_TRIGGER = 1811;
export const CONSTRAINT_UNIQUE = 2067;
export const CONSTRAINT_VTAB = 2323;
export const NOTICE_RECOVER_WAL = 283;
export const NOTICE_RECOVER_ROLLBACK = 539;
export const NOTICE_RBU = 795;
export const WARNING_AUTOINDEX = 284;
export const AUTH_USER = 279;
export const OK_LOAD_PERMANENTLY = 256;
export const OK_SYMLINK = 512;
export const OPEN_READONLY = 1;
export const OPEN_READWRITE = 2;
export const OPEN_CREATE = 4;
export const OPEN_DELETEONCLOSE = 8;
export const OPEN_EXCLUSIVE = 16;
export const OPEN_AUTOPROXY = 32;
export const OPEN_URI = 64;
export const OPEN_MEMORY = 128;
export const OPEN_MAIN_DB = 256;
export const OPEN_TEMP_DB = 512;
export const OPEN_TRANSIENT_DB = 1024;
export const OPEN_MAIN_JOURNAL = 2048;
export const OPEN_TEMP_JOURNAL = 4096;
export const OPEN_SUBJOURNAL = 8192;
export const OPEN_SUPER_JOURNAL = 16384;
export const OPEN_NOMUTEX = 32768;
export const OPEN_FULLMUTEX = 65536;
export const OPEN_SHAREDCACHE = 131072;
export const OPEN_PRIVATECACHE = 262144;
export const OPEN_WAL = 524288;
export const OPEN_NOFOLLOW = 16777216;
export const OPEN_EXRESCODE = 33554432;
export const OPEN_MASTER_JOURNAL = 16384;
export const IOCAP_ATOMIC = 1;
export const IOCAP_ATOMIC512 = 2;
export const IOCAP_ATOMIC1K = 4;
export const IOCAP_ATOMIC2K = 8;
export const IOCAP_ATOMIC4K = 16;
export const IOCAP_ATOMIC8K = 32;
export const IOCAP_ATOMIC16K = 64;
export const IOCAP_ATOMIC32K = 128;
export const IOCAP_ATOMIC64K = 256;
export const IOCAP_SAFE_APPEND = 512;
export const IOCAP_SEQUENTIAL = 1024;
export const IOCAP_UNDELETABLE_WHEN_OPEN = 2048;
export const IOCAP_POWERSAFE_OVERWRITE = 4096;
export const IOCAP_IMMUTABLE = 8192;
export const IOCAP_BATCH_ATOMIC = 16384;
export const LOCK_NONE = 0;
export const LOCK_SHARED = 1;
export const LOCK_RESERVED = 2;
export const LOCK_PENDING = 3;
export const LOCK_EXCLUSIVE = 4;
export const SYNC_NORMAL = 2;
export const SYNC_FULL = 3;
export const SYNC_DATAONLY = 16;
export const FCNTL_LOCKSTATE = 1;
export const FCNTL_GET_LOCKPROXYFILE = 2;
export const FCNTL_SET_LOCKPROXYFILE = 3;
export const FCNTL_LAST_ERRNO = 4;
export const FCNTL_SIZE_HINT = 5;
export const FCNTL_CHUNK_SIZE = 6;
export const FCNTL_FILE_POINTER = 7;
export const FCNTL_SYNC_OMITTED = 8;
export const FCNTL_WIN32_AV_RETRY = 9;
export const FCNTL_PERSIST_WAL = 10;
export const FCNTL_OVERWRITE = 11;
export const FCNTL_VFSNAME = 12;
export const FCNTL_POWERSAFE_OVERWRITE = 13;
export const FCNTL_PRAGMA = 14;
export const FCNTL_BUSYHANDLER = 15;
export const FCNTL_TEMPFILENAME = 16;
export const FCNTL_MMAP_SIZE = 18;
export const FCNTL_TRACE = 19;
export const FCNTL_HAS_MOVED = 20;
export const FCNTL_SYNC = 21;
export const FCNTL_COMMIT_PHASETWO = 22;
export const FCNTL_WIN32_SET_HANDLE = 23;
export const FCNTL_WAL_BLOCK = 24;
export const FCNTL_ZIPVFS = 25;
export const FCNTL_RBU = 26;
export const FCNTL_VFS_POINTER = 27;
export const FCNTL_JOURNAL_POINTER = 28;
export const FCNTL_WIN32_GET_HANDLE = 29;
export const FCNTL_PDB = 30;
export const FCNTL_BEGIN_ATOMIC_WRITE = 31;
export const FCNTL_COMMIT_ATOMIC_WRITE = 32;
export const FCNTL_ROLLBACK_ATOMIC_WRITE = 33;
export const FCNTL_LOCK_TIMEOUT = 34;
export const FCNTL_DATA_VERSION = 35;
export const FCNTL_SIZE_LIMIT = 36;
export const FCNTL_CKPT_DONE = 37;
export const FCNTL_RESERVE_BYTES = 38;
export const FCNTL_CKPT_START = 39;
export const FCNTL_EXTERNAL_READER = 40;
export const FCNTL_CKSM_FILE = 41;
export const FCNTL_RESET_CACHE = 42;
export const ACCESS_EXISTS = 0;
export const ACCESS_READWRITE = 1;
export const ACCESS_READ = 2;
export const SHM_UNLOCK = 1;
export const SHM_LOCK = 2;
export const SHM_SHARED = 4;
export const SHM_EXCLUSIVE = 8;
export const SHM_NLOCK = 8;
export const CONFIG_SINGLETHREAD = 1;
export const CONFIG_MULTITHREAD = 2;
export const CONFIG_SERIALIZED = 3;
export const CONFIG_MALLOC = 4;
export const CONFIG_GETMALLOC = 5;
export const CONFIG_SCRATCH = 6;
export const CONFIG_PAGECACHE = 7;
export const CONFIG_HEAP = 8;
export const CONFIG_MEMSTATUS = 9;
export const CONFIG_MUTEX = 10;
export const CONFIG_GETMUTEX = 11;
export const CONFIG_LOOKASIDE = 13;
export const CONFIG_PCACHE = 14;
export const CONFIG_GETPCACHE = 15;
export const CONFIG_LOG = 16;
export const CONFIG_URI = 17;
export const CONFIG_PCACHE2 = 18;
export const CONFIG_GETPCACHE2 = 19;
export const CONFIG_COVERING_INDEX_SCAN = 20;
export const CONFIG_SQLLOG = 21;
export const CONFIG_MMAP_SIZE = 22;
export const CONFIG_WIN32_HEAPSIZE = 23;
export const CONFIG_PCACHE_HDRSZ = 24;
export const CONFIG_PMASZ = 25;
export const CONFIG_STMTJRNL_SPILL = 26;
export const CONFIG_SMALL_MALLOC = 27;
export const CONFIG_SORTERREF_SIZE = 28;
export const CONFIG_MEMDB_MAXSIZE = 29;
export const DBCONFIG_MAINDBNAME = 1000;
export const DBCONFIG_LOOKASIDE = 1001;
export const DBCONFIG_ENABLE_FKEY = 1002;
export const DBCONFIG_ENABLE_TRIGGER = 1003;
export const DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004;
export const DBCONFIG_ENABLE_LOAD_EXTENSION = 1005;
export const DBCONFIG_NO_CKPT_ON_CLOSE = 1006;
export const DBCONFIG_ENABLE_QPSG = 1007;
export const DBCONFIG_TRIGGER_EQP = 1008;
export const DBCONFIG_RESET_DATABASE = 1009;
export const DBCONFIG_DEFENSIVE = 1010;
export const DBCONFIG_WRITABLE_SCHEMA = 1011;
export const DBCONFIG_LEGACY_ALTER_TABLE = 1012;
export const DBCONFIG_DQS_DML = 1013;
export const DBCONFIG_DQS_DDL = 1014;
export const DBCONFIG_ENABLE_VIEW = 1015;
export const DBCONFIG_LEGACY_FILE_FORMAT = 1016;
export const DBCONFIG_TRUSTED_SCHEMA = 1017;
export const DBCONFIG_STMT_SCANSTATUS = 1018;
export const DBCONFIG_REVERSE_SCANORDER = 1019;
export const DBCONFIG_MAX = 1019;
export const DENY = 1;
export const IGNORE = 2;
export const CREATE_INDEX = 1;
export const CREATE_TABLE = 2;
export const CREATE_TEMP_INDEX = 3;
export const CREATE_TEMP_TABLE = 4;
export const CREATE_TEMP_TRIGGER = 5;
export const CREATE_TEMP_VIEW = 6;
export const CREATE_TRIGGER = 7;
export const CREATE_VIEW = 8;
export const DELETE = 9;
export const DROP_INDEX = 10;
export const DROP_TABLE = 11;
export const DROP_TEMP_INDEX = 12;
export const DROP_TEMP_TABLE = 13;
export const DROP_TEMP_TRIGGER = 14;
export const DROP_TEMP_VIEW = 15;
export const DROP_TRIGGER = 16;
export const DROP_VIEW = 17;
export const INSERT = 18;
export const PRAGMA = 19;
export const READ = 20;
export const SELECT = 21;
export const TRANSACTION = 22;
export const UPDATE = 23;
export const ATTACH = 24;
export const DETACH = 25;
export const ALTER_TABLE = 26;
export const REINDEX = 27;
export const ANALYZE = 28;
export const CREATE_VTABLE = 29;
export const DROP_VTABLE = 30;
export const FUNCTION = 31;
export const SAVEPOINT = 32;
export const COPY = 0;
export const RECURSIVE = 33;
export const TRACE_STMT = 1;
export const TRACE_PROFILE = 2;
export const TRACE_ROW = 4;
export const TRACE_CLOSE = 8;
export const LIMIT_LENGTH = 0;
export const LIMIT_SQL_LENGTH = 1;
export const LIMIT_COLUMN = 2;
export const LIMIT_EXPR_DEPTH = 3;
export const LIMIT_COMPOUND_SELECT = 4;
export const LIMIT_VDBE_OP = 5;
export const LIMIT_FUNCTION_ARG = 6;
export const LIMIT_ATTACHED = 7;
export const LIMIT_LIKE_PATTERN_LENGTH = 8;
export const LIMIT_VARIABLE_NUMBER = 9;
export const LIMIT_TRIGGER_DEPTH = 10;
export const LIMIT_WORKER_THREADS = 11;
export const PREPARE_PERSISTENT = 1;
export const PREPARE_NORMALIZE = 2;
export const PREPARE_NO_VTAB = 4;
export const INTEGER = 1;
export const FLOAT = 2;
export const BLOB = 4;
export const NULL = 5;
export const TEXT = 3;
export const UTF8 = 1;
export const UTF16LE = 2;
export const UTF16BE = 3;
export const UTF16 = 4;
export const ANY = 5;
export const UTF16_ALIGNED = 8;
export const DETERMINISTIC = 2048;
export const DIRECTONLY = 524288;
export const SUBTYPE = 1048576;
export const INNOCUOUS = 2097152;
export const RESULT_SUBTYPE = 16777216;
export const WIN32_DATA_DIRECTORY_TYPE = 1;
export const WIN32_TEMP_DIRECTORY_TYPE = 2;
export const TXN_NONE = 0;
export const TXN_READ = 1;
export const TXN_WRITE = 2;
export const INDEX_SCAN_UNIQUE = 1;
export const INDEX_CONSTRAINT_EQ = 2;
export const INDEX_CONSTRAINT_GT = 4;
export const INDEX_CONSTRAINT_LE = 8;
export const INDEX_CONSTRAINT_LT = 16;
export const INDEX_CONSTRAINT_GE = 32;
export const INDEX_CONSTRAINT_MATCH = 64;
export const INDEX_CONSTRAINT_LIKE = 65;
export const INDEX_CONSTRAINT_GLOB = 66;
export const INDEX_CONSTRAINT_REGEXP = 67;
export const INDEX_CONSTRAINT_NE = 68;
export const INDEX_CONSTRAINT_ISNOT = 69;
export const INDEX_CONSTRAINT_ISNOTNULL = 70;
export const INDEX_CONSTRAINT_ISNULL = 71;
export const INDEX_CONSTRAINT_IS = 72;
export const INDEX_CONSTRAINT_LIMIT = 73;
export const INDEX_CONSTRAINT_OFFSET = 74;
export const INDEX_CONSTRAINT_FUNCTION = 150;
export const MUTEX_FAST = 0;
export const MUTEX_RECURSIVE = 1;
export const MUTEX_STATIC_MAIN = 2;
export const MUTEX_STATIC_MEM = 3;
export const MUTEX_STATIC_MEM2 = 4;
export const MUTEX_STATIC_OPEN = 4;
export const MUTEX_STATIC_PRNG = 5;
export const MUTEX_STATIC_LRU = 6;
export const MUTEX_STATIC_LRU2 = 7;
export const MUTEX_STATIC_PMEM = 7;
export const MUTEX_STATIC_APP1 = 8;
export const MUTEX_STATIC_APP2 = 9;
export const MUTEX_STATIC_APP3 = 10;
export const MUTEX_STATIC_VFS1 = 11;
export const MUTEX_STATIC_VFS2 = 12;
export const MUTEX_STATIC_VFS3 = 13;
export const MUTEX_STATIC_MASTER = 2;
export const TESTCTRL_FIRST = 5;
export const TESTCTRL_PRNG_SAVE = 5;
export const TESTCTRL_PRNG_RESTORE = 6;
export const TESTCTRL_PRNG_RESET = 7;
export const TESTCTRL_FK_NO_ACTION = 7;
export const TESTCTRL_BITVEC_TEST = 8;
export const TESTCTRL_FAULT_INSTALL = 9;
export const TESTCTRL_BENIGN_MALLOC_HOOKS = 10;
export const TESTCTRL_PENDING_BYTE = 11;
export const TESTCTRL_ASSERT = 12;
export const TESTCTRL_ALWAYS = 13;
export const TESTCTRL_RESERVE = 14;
export const TESTCTRL_OPTIMIZATIONS = 15;
export const TESTCTRL_ISKEYWORD = 16;
export const TESTCTRL_SCRATCHMALLOC = 17;
export const TESTCTRL_INTERNAL_FUNCTIONS = 17;
export const TESTCTRL_LOCALTIME_FAULT = 18;
export const TESTCTRL_EXPLAIN_STMT = 19;
export const TESTCTRL_ONCE_RESET_THRESHOLD = 19;
export const TESTCTRL_NEVER_CORRUPT = 20;
export const TESTCTRL_VDBE_COVERAGE = 21;
export const TESTCTRL_BYTEORDER = 22;
export const TESTCTRL_ISINIT = 23;
export const TESTCTRL_SORTER_MMAP = 24;
export const TESTCTRL_IMPOSTER = 25;
export const TESTCTRL_PARSER_COVERAGE = 26;
export const TESTCTRL_RESULT_INTREAL = 27;
export const TESTCTRL_PRNG_SEED = 28;
export const TESTCTRL_EXTRA_SCHEMA_CHECKS = 29;
export const TESTCTRL_SEEK_COUNT = 30;
export const TESTCTRL_TRACEFLAGS = 31;
export const TESTCTRL_TUNE = 32;
export const TESTCTRL_LOGEST = 33;
export const TESTCTRL_USELONGDOUBLE = 34;
export const TESTCTRL_LAST = 34;
export const STATUS_MEMORY_USED = 0;
export const STATUS_PAGECACHE_USED = 1;
export const STATUS_PAGECACHE_OVERFLOW = 2;
export const STATUS_SCRATCH_USED = 3;
export const STATUS_SCRATCH_OVERFLOW = 4;
export const STATUS_MALLOC_SIZE = 5;
export const STATUS_PARSER_STACK = 6;
export const STATUS_PAGECACHE_SIZE = 7;
export const STATUS_SCRATCH_SIZE = 8;
export const STATUS_MALLOC_COUNT = 9;
export const DBSTATUS_LOOKASIDE_USED = 0;
export const DBSTATUS_CACHE_USED = 1;
export const DBSTATUS_SCHEMA_USED = 2;
export const DBSTATUS_STMT_USED = 3;
export const DBSTATUS_LOOKASIDE_HIT = 4;
export const DBSTATUS_LOOKASIDE_MISS_SIZE = 5;
export const DBSTATUS_LOOKASIDE_MISS_FULL = 6;
export const DBSTATUS_CACHE_HIT = 7;
export const DBSTATUS_CACHE_MISS = 8;
export const DBSTATUS_CACHE_WRITE = 9;
export const DBSTATUS_DEFERRED_FKS = 10;
export const DBSTATUS_CACHE_USED_SHARED = 11;
export const DBSTATUS_CACHE_SPILL = 12;
export const DBSTATUS_MAX = 12;
export const STMTSTATUS_FULLSCAN_STEP = 1;
export const STMTSTATUS_SORT = 2;
export const STMTSTATUS_AUTOINDEX = 3;
export const STMTSTATUS_VM_STEP = 4;
export const STMTSTATUS_REPREPARE = 5;
export const STMTSTATUS_RUN = 6;
export const STMTSTATUS_FILTER_MISS = 7;
export const STMTSTATUS_FILTER_HIT = 8;
export const STMTSTATUS_MEMUSED = 99;
export const CHECKPOINT_PASSIVE = 0;
export const CHECKPOINT_FULL = 1;
export const CHECKPOINT_RESTART = 2;
export const CHECKPOINT_TRUNCATE = 3;
export const VTAB_CONSTRAINT_SUPPORT = 1;
export const VTAB_INNOCUOUS = 2;
export const VTAB_DIRECTONLY = 3;
export const VTAB_USES_ALL_SCHEMAS = 4;
export const ROLLBACK = 1;
export const FAIL = 3;
export const REPLACE = 5;
export const SCANSTAT_NLOOP = 0;
export const SCANSTAT_NVISIT = 1;
export const SCANSTAT_EST = 2;
export const SCANSTAT_NAME = 3;
export const SCANSTAT_EXPLAIN = 4;
export const SCANSTAT_SELECTID = 5;
export const SCANSTAT_PARENTID = 6;
export const SCANSTAT_NCYCLE = 7;
export const SCANSTAT_COMPLEX = 1;
export const SERIALIZE_NOCOPY = 1;
export const DESERIALIZE_FREEONCLOSE = 1;
export const DESERIALIZE_RESIZEABLE = 2;
export const DESERIALIZE_READONLY = 4;
export const WASI = 1;
export const THREADSAFE = 0;
export const SESSION_OBJCONFIG_SIZE = 1;
export const SESSION_OBJCONFIG_ROWID = 2;
export const CHANGESETSTART_INVERT = 2;
export const CHANGESETAPPLY_NOSAVEPOINT = 1;
export const CHANGESETAPPLY_INVERT = 2;
export const CHANGESETAPPLY_IGNORENOOP = 4;
export const CHANGESETAPPLY_FKNOACTION = 8;
export const CHANGESET_DATA = 1;
export const CHANGESET_NOTFOUND = 2;
export const CHANGESET_CONFLICT = 3;
export const CHANGESET_CONSTRAINT = 4;
export const CHANGESET_FOREIGN_KEY = 5;
export const CHANGESET_OMIT = 0;
export const CHANGESET_REPLACE = 1;
export const CHANGESET_ABORT = 2;
export const SESSION_CONFIG_STRMSIZE = 1;

export const ResultCode = {
	"OK": OK,
	"ERROR": ERROR,
	"INTERNAL": INTERNAL,
	"PERM": PERM,
	"ABORT": ABORT,
	"BUSY": BUSY,
	"LOCKED": LOCKED,
	"NOMEM": NOMEM,
	"READONLY": READONLY,
	"INTERRUPT": INTERRUPT,
	"IOERR": IOERR,
	"CORRUPT": CORRUPT,
	"NOTFOUND": NOTFOUND,
	"FULL": FULL,
	"CANTOPEN": CANTOPEN,
	"PROTOCOL": PROTOCOL,
	"EMPTY": EMPTY,
	"SCHEMA": SCHEMA,
	"TOOBIG": TOOBIG,
	"CONSTRAINT": CONSTRAINT,
	"MISMATCH": MISMATCH,
	"MISUSE": MISUSE,
	"NOLFS": NOLFS,
	"AUTH": AUTH,
	"FORMAT": FORMAT,
	"RANGE": RANGE,
	"NOTADB": NOTADB,
	"NOTICE": NOTICE,
	"WARNING": WARNING,
	"ROW": ROW,
	"DONE": DONE,
	[OK]: "OK",
	[ERROR]: "ERROR",
	[INTERNAL]: "INTERNAL",
	[PERM]: "PERM",
	[ABORT]: "ABORT",
	[BUSY]: "BUSY",
	[LOCKED]: "LOCKED",
	[NOMEM]: "NOMEM",
	[READONLY]: "READONLY",
	[INTERRUPT]: "INTERRUPT",
	[IOERR]: "IOERR",
	[CORRUPT]: "CORRUPT",
	[NOTFOUND]: "NOTFOUND",
	[FULL]: "FULL",
	[CANTOPEN]: "CANTOPEN",
	[PROTOCOL]: "PROTOCOL",
	[EMPTY]: "EMPTY",
	[SCHEMA]: "SCHEMA",
	[TOOBIG]: "TOOBIG",
	[CONSTRAINT]: "CONSTRAINT",
	[MISMATCH]: "MISMATCH",
	[MISUSE]: "MISUSE",
	[NOLFS]: "NOLFS",
	[AUTH]: "AUTH",
	[FORMAT]: "FORMAT",
	[RANGE]: "RANGE",
	[NOTADB]: "NOTADB",
	[NOTICE]: "NOTICE",
	[WARNING]: "WARNING",
	[ROW]: "ROW",
	[DONE]: "DONE",
} as const;
export type ResultCode = typeof ResultCode[keyof typeof ResultCode & string];

export const ExtendedResultCode = {
	"ERROR_MISSING_COLLSEQ": ERROR_MISSING_COLLSEQ,
	"ERROR_RETRY": ERROR_RETRY,
	"ERROR_SNAPSHOT": ERROR_SNAPSHOT,
	"IOERR_READ": IOERR_READ,
	"IOERR_SHORT_READ": IOERR_SHORT_READ,
	"IOERR_WRITE": IOERR_WRITE,
	"IOERR_FSYNC": IOERR_FSYNC,
	"IOERR_DIR_FSYNC": IOERR_DIR_FSYNC,
	"IOERR_TRUNCATE": IOERR_TRUNCATE,
	"IOERR_FSTAT": IOERR_FSTAT,
	"IOERR_UNLOCK": IOERR_UNLOCK,
	"IOERR_RDLOCK": IOERR_RDLOCK,
	"IOERR_DELETE": IOERR_DELETE,
	"IOERR_BLOCKED": IOERR_BLOCKED,
	"IOERR_NOMEM": IOERR_NOMEM,
	"IOERR_ACCESS": IOERR_ACCESS,
	"IOERR_CHECKRESERVEDLOCK": IOERR_CHECKRESERVEDLOCK,
	"IOERR_LOCK": IOERR_LOCK,
	"IOERR_CLOSE": IOERR_CLOSE,
	"IOERR_DIR_CLOSE": IOERR_DIR_CLOSE,
	"IOERR_SHMOPEN": IOERR_SHMOPEN,
	"IOERR_SHMSIZE": IOERR_SHMSIZE,
	"IOERR_SHMLOCK": IOERR_SHMLOCK,
	"IOERR_SHMMAP": IOERR_SHMMAP,
	"IOERR_SEEK": IOERR_SEEK,
	"IOERR_DELETE_NOENT": IOERR_DELETE_NOENT,
	"IOERR_MMAP": IOERR_MMAP,
	"IOERR_GETTEMPPATH": IOERR_GETTEMPPATH,
	"IOERR_CONVPATH": IOERR_CONVPATH,
	"IOERR_VNODE": IOERR_VNODE,
	"IOERR_AUTH": IOERR_AUTH,
	"IOERR_BEGIN_ATOMIC": IOERR_BEGIN_ATOMIC,
	"IOERR_COMMIT_ATOMIC": IOERR_COMMIT_ATOMIC,
	"IOERR_ROLLBACK_ATOMIC": IOERR_ROLLBACK_ATOMIC,
	"IOERR_DATA": IOERR_DATA,
	"IOERR_CORRUPTFS": IOERR_CORRUPTFS,
	"IOERR_IN_PAGE": IOERR_IN_PAGE,
	"CANTOPEN_NOTEMPDIR": CANTOPEN_NOTEMPDIR,
	"CANTOPEN_ISDIR": CANTOPEN_ISDIR,
	"CANTOPEN_FULLPATH": CANTOPEN_FULLPATH,
	"CANTOPEN_CONVPATH": CANTOPEN_CONVPATH,
	"CANTOPEN_DIRTYWAL": CANTOPEN_DIRTYWAL,
	"CANTOPEN_SYMLINK": CANTOPEN_SYMLINK,
	"CORRUPT_VTAB": CORRUPT_VTAB,
	"CORRUPT_SEQUENCE": CORRUPT_SEQUENCE,
	"CORRUPT_INDEX": CORRUPT_INDEX,
	"READONLY_RECOVERY": READONLY_RECOVERY,
	"READONLY_CANTLOCK": READONLY_CANTLOCK,
	"READONLY_ROLLBACK": READONLY_ROLLBACK,
	"READONLY_DBMOVED": READONLY_DBMOVED,
	"READONLY_CANTINIT": READONLY_CANTINIT,
	"READONLY_DIRECTORY": READONLY_DIRECTORY,
	"ABORT_ROLLBACK": ABORT_ROLLBACK,
	"CONSTRAINT_CHECK": CONSTRAINT_CHECK,
	"CONSTRAINT_COMMITHOOK": CONSTRAINT_COMMITHOOK,
	"CONSTRAINT_FOREIGNKEY": CONSTRAINT_FOREIGNKEY,
	"CONSTRAINT_FUNCTION": CONSTRAINT_FUNCTION,
	"CONSTRAINT_NOTNULL": CONSTRAINT_NOTNULL,
	"CONSTRAINT_PRIMARYKEY": CONSTRAINT_PRIMARYKEY,
	"CONSTRAINT_TRIGGER": CONSTRAINT_TRIGGER,
	"CONSTRAINT_UNIQUE": CONSTRAINT_UNIQUE,
	"CONSTRAINT_VTAB": CONSTRAINT_VTAB,
	"NOTICE_RECOVER_WAL": NOTICE_RECOVER_WAL,
	"NOTICE_RECOVER_ROLLBACK": NOTICE_RECOVER_ROLLBACK,
	"NOTICE_RBU": NOTICE_RBU,
	"WARNING_AUTOINDEX": WARNING_AUTOINDEX,
	"AUTH_USER": AUTH_USER,
	"OK_LOAD_PERMANENTLY": OK_LOAD_PERMANENTLY,
	"OK_SYMLINK": OK_SYMLINK,
	[ERROR_MISSING_COLLSEQ]: "ERROR_MISSING_COLLSEQ",
	[ERROR_RETRY]: "ERROR_RETRY",
	[ERROR_SNAPSHOT]: "ERROR_SNAPSHOT",
	[IOERR_READ]: "IOERR_READ",
	[IOERR_SHORT_READ]: "IOERR_SHORT_READ",
	[IOERR_WRITE]: "IOERR_WRITE",
	[IOERR_FSYNC]: "IOERR_FSYNC",
	[IOERR_DIR_FSYNC]: "IOERR_DIR_FSYNC",
	[IOERR_TRUNCATE]: "IOERR_TRUNCATE",
	[IOERR_FSTAT]: "IOERR_FSTAT",
	[IOERR_UNLOCK]: "IOERR_UNLOCK",
	[IOERR_RDLOCK]: "IOERR_RDLOCK",
	[IOERR_DELETE]: "IOERR_DELETE",
	[IOERR_BLOCKED]: "IOERR_BLOCKED",
	[IOERR_NOMEM]: "IOERR_NOMEM",
	[IOERR_ACCESS]: "IOERR_ACCESS",
	[IOERR_CHECKRESERVEDLOCK]: "IOERR_CHECKRESERVEDLOCK",
	[IOERR_LOCK]: "IOERR_LOCK",
	[IOERR_CLOSE]: "IOERR_CLOSE",
	[IOERR_DIR_CLOSE]: "IOERR_DIR_CLOSE",
	[IOERR_SHMOPEN]: "IOERR_SHMOPEN",
	[IOERR_SHMSIZE]: "IOERR_SHMSIZE",
	[IOERR_SHMLOCK]: "IOERR_SHMLOCK",
	[IOERR_SHMMAP]: "IOERR_SHMMAP",
	[IOERR_SEEK]: "IOERR_SEEK",
	[IOERR_DELETE_NOENT]: "IOERR_DELETE_NOENT",
	[IOERR_MMAP]: "IOERR_MMAP",
	[IOERR_GETTEMPPATH]: "IOERR_GETTEMPPATH",
	[IOERR_CONVPATH]: "IOERR_CONVPATH",
	[IOERR_VNODE]: "IOERR_VNODE",
	[IOERR_AUTH]: "IOERR_AUTH",
	[IOERR_BEGIN_ATOMIC]: "IOERR_BEGIN_ATOMIC",
	[IOERR_COMMIT_ATOMIC]: "IOERR_COMMIT_ATOMIC",
	[IOERR_ROLLBACK_ATOMIC]: "IOERR_ROLLBACK_ATOMIC",
	[IOERR_DATA]: "IOERR_DATA",
	[IOERR_CORRUPTFS]: "IOERR_CORRUPTFS",
	[IOERR_IN_PAGE]: "IOERR_IN_PAGE",
	[CANTOPEN_NOTEMPDIR]: "CANTOPEN_NOTEMPDIR",
	[CANTOPEN_ISDIR]: "CANTOPEN_ISDIR",
	[CANTOPEN_FULLPATH]: "CANTOPEN_FULLPATH",
	[CANTOPEN_CONVPATH]: "CANTOPEN_CONVPATH",
	[CANTOPEN_DIRTYWAL]: "CANTOPEN_DIRTYWAL",
	[CANTOPEN_SYMLINK]: "CANTOPEN_SYMLINK",
	[CORRUPT_VTAB]: "CORRUPT_VTAB",
	[CORRUPT_SEQUENCE]: "CORRUPT_SEQUENCE",
	[CORRUPT_INDEX]: "CORRUPT_INDEX",
	[READONLY_RECOVERY]: "READONLY_RECOVERY",
	[READONLY_CANTLOCK]: "READONLY_CANTLOCK",
	[READONLY_ROLLBACK]: "READONLY_ROLLBACK",
	[READONLY_DBMOVED]: "READONLY_DBMOVED",
	[READONLY_CANTINIT]: "READONLY_CANTINIT",
	[READONLY_DIRECTORY]: "READONLY_DIRECTORY",
	[ABORT_ROLLBACK]: "ABORT_ROLLBACK",
	[CONSTRAINT_CHECK]: "CONSTRAINT_CHECK",
	[CONSTRAINT_COMMITHOOK]: "CONSTRAINT_COMMITHOOK",
	[CONSTRAINT_FOREIGNKEY]: "CONSTRAINT_FOREIGNKEY",
	[CONSTRAINT_FUNCTION]: "CONSTRAINT_FUNCTION",
	[CONSTRAINT_NOTNULL]: "CONSTRAINT_NOTNULL",
	[CONSTRAINT_PRIMARYKEY]: "CONSTRAINT_PRIMARYKEY",
	[CONSTRAINT_TRIGGER]: "CONSTRAINT_TRIGGER",
	[CONSTRAINT_UNIQUE]: "CONSTRAINT_UNIQUE",
	[CONSTRAINT_VTAB]: "CONSTRAINT_VTAB",
	[NOTICE_RECOVER_WAL]: "NOTICE_RECOVER_WAL",
	[NOTICE_RECOVER_ROLLBACK]: "NOTICE_RECOVER_ROLLBACK",
	[NOTICE_RBU]: "NOTICE_RBU",
	[WARNING_AUTOINDEX]: "WARNING_AUTOINDEX",
	[AUTH_USER]: "AUTH_USER",
	[OK_LOAD_PERMANENTLY]: "OK_LOAD_PERMANENTLY",
	[OK_SYMLINK]: "OK_SYMLINK",
} as const;
export type ExtendedResultCode = typeof ExtendedResultCode[keyof typeof ExtendedResultCode & string];

export const OpenFlag = {
	"READONLY": OPEN_READONLY,
	"READWRITE": OPEN_READWRITE,
	"CREATE": OPEN_CREATE,
	"DELETEONCLOSE": OPEN_DELETEONCLOSE,
	"EXCLUSIVE": OPEN_EXCLUSIVE,
	"AUTOPROXY": OPEN_AUTOPROXY,
	"URI": OPEN_URI,
	"MEMORY": OPEN_MEMORY,
	"MAIN_DB": OPEN_MAIN_DB,
	"TEMP_DB": OPEN_TEMP_DB,
	"TRANSIENT_DB": OPEN_TRANSIENT_DB,
	"MAIN_JOURNAL": OPEN_MAIN_JOURNAL,
	"TEMP_JOURNAL": OPEN_TEMP_JOURNAL,
	"SUBJOURNAL": OPEN_SUBJOURNAL,
	"SUPER_JOURNAL": OPEN_SUPER_JOURNAL,
	"NOMUTEX": OPEN_NOMUTEX,
	"FULLMUTEX": OPEN_FULLMUTEX,
	"SHAREDCACHE": OPEN_SHAREDCACHE,
	"PRIVATECACHE": OPEN_PRIVATECACHE,
	"WAL": OPEN_WAL,
	"NOFOLLOW": OPEN_NOFOLLOW,
	"EXRESCODE": OPEN_EXRESCODE,
	[OPEN_READONLY]: "READONLY",
	[OPEN_READWRITE]: "READWRITE",
	[OPEN_CREATE]: "CREATE",
	[OPEN_DELETEONCLOSE]: "DELETEONCLOSE",
	[OPEN_EXCLUSIVE]: "EXCLUSIVE",
	[OPEN_AUTOPROXY]: "AUTOPROXY",
	[OPEN_URI]: "URI",
	[OPEN_MEMORY]: "MEMORY",
	[OPEN_MAIN_DB]: "MAIN_DB",
	[OPEN_TEMP_DB]: "TEMP_DB",
	[OPEN_TRANSIENT_DB]: "TRANSIENT_DB",
	[OPEN_MAIN_JOURNAL]: "MAIN_JOURNAL",
	[OPEN_TEMP_JOURNAL]: "TEMP_JOURNAL",
	[OPEN_SUBJOURNAL]: "SUBJOURNAL",
	[OPEN_SUPER_JOURNAL]: "SUPER_JOURNAL",
	[OPEN_NOMUTEX]: "NOMUTEX",
	[OPEN_FULLMUTEX]: "FULLMUTEX",
	[OPEN_SHAREDCACHE]: "SHAREDCACHE",
	[OPEN_PRIVATECACHE]: "PRIVATECACHE",
	[OPEN_WAL]: "WAL",
	[OPEN_NOFOLLOW]: "NOFOLLOW",
	[OPEN_EXRESCODE]: "EXRESCODE",
} as const;
export type OpenFlag = typeof OpenFlag[keyof typeof OpenFlag & string];

export const DeviceCharacteristics = {
	"ATOMIC": IOCAP_ATOMIC,
	"ATOMIC512": IOCAP_ATOMIC512,
	"ATOMIC1K": IOCAP_ATOMIC1K,
	"ATOMIC2K": IOCAP_ATOMIC2K,
	"ATOMIC4K": IOCAP_ATOMIC4K,
	"ATOMIC8K": IOCAP_ATOMIC8K,
	"ATOMIC16K": IOCAP_ATOMIC16K,
	"ATOMIC32K": IOCAP_ATOMIC32K,
	"ATOMIC64K": IOCAP_ATOMIC64K,
	"SAFE_APPEND": IOCAP_SAFE_APPEND,
	"SEQUENTIAL": IOCAP_SEQUENTIAL,
	"UNDELETABLE_WHEN_OPEN": IOCAP_UNDELETABLE_WHEN_OPEN,
	"POWERSAFE_OVERWRITE": IOCAP_POWERSAFE_OVERWRITE,
	"IMMUTABLE": IOCAP_IMMUTABLE,
	"BATCH_ATOMIC": IOCAP_BATCH_ATOMIC,
	[IOCAP_ATOMIC]: "ATOMIC",
	[IOCAP_ATOMIC512]: "ATOMIC512",
	[IOCAP_ATOMIC1K]: "ATOMIC1K",
	[IOCAP_ATOMIC2K]: "ATOMIC2K",
	[IOCAP_ATOMIC4K]: "ATOMIC4K",
	[IOCAP_ATOMIC8K]: "ATOMIC8K",
	[IOCAP_ATOMIC16K]: "ATOMIC16K",
	[IOCAP_ATOMIC32K]: "ATOMIC32K",
	[IOCAP_ATOMIC64K]: "ATOMIC64K",
	[IOCAP_SAFE_APPEND]: "SAFE_APPEND",
	[IOCAP_SEQUENTIAL]: "SEQUENTIAL",
	[IOCAP_UNDELETABLE_WHEN_OPEN]: "UNDELETABLE_WHEN_OPEN",
	[IOCAP_POWERSAFE_OVERWRITE]: "POWERSAFE_OVERWRITE",
	[IOCAP_IMMUTABLE]: "IMMUTABLE",
	[IOCAP_BATCH_ATOMIC]: "BATCH_ATOMIC",
} as const;
export type DeviceCharacteristics = typeof DeviceCharacteristics[keyof typeof DeviceCharacteristics & string];

export const LockLevel = {
	"NONE": LOCK_NONE,
	"SHARED": LOCK_SHARED,
	"RESERVED": LOCK_RESERVED,
	"PENDING": LOCK_PENDING,
	"EXCLUSIVE": LOCK_EXCLUSIVE,
	[LOCK_NONE]: "NONE",
	[LOCK_SHARED]: "SHARED",
	[LOCK_RESERVED]: "RESERVED",
	[LOCK_PENDING]: "PENDING",
	[LOCK_EXCLUSIVE]: "EXCLUSIVE",
} as const;
export type LockLevel = typeof LockLevel[keyof typeof LockLevel & string];

export const SyncFlag = {
	"NORMAL": SYNC_NORMAL,
	"FULL": SYNC_FULL,
	"DATAONLY": SYNC_DATAONLY,
	[SYNC_NORMAL]: "NORMAL",
	[SYNC_FULL]: "FULL",
	[SYNC_DATAONLY]: "DATAONLY",
} as const;
export type SyncFlag = typeof SyncFlag[keyof typeof SyncFlag & string];

export const AccessFlag = {
	"EXISTS": ACCESS_EXISTS,
	"READWRITE": ACCESS_READWRITE,
	"READ": ACCESS_READ,
	[ACCESS_EXISTS]: "EXISTS",
	[ACCESS_READWRITE]: "READWRITE",
	[ACCESS_READ]: "READ",
} as const;
export type AccessFlag = typeof AccessFlag[keyof typeof AccessFlag & string];

export const Datatype = {
	"INTEGER": INTEGER,
	"FLOAT": FLOAT,
	"BLOB": BLOB,
	"NULL": NULL,
	"TEXT": TEXT,
	[INTEGER]: "INTEGER",
	[FLOAT]: "FLOAT",
	[BLOB]: "BLOB",
	[NULL]: "NULL",
	[TEXT]: "TEXT",
} as const;
export type Datatype = typeof Datatype[keyof typeof Datatype & string];

